/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'ecommerce_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ADSIMAGE = 'assets/images/adsImage.png';
  static const String ADSIMAGE2 = 'assets/images/adsImage2.png';
  static const String ADSIMAGE3 = 'assets/images/adsImage3.png';
}
