/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'ecommerce_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CATEGORY = 'assets/icons/category.png';
  static const String HEART = 'assets/icons/heart.png';
  static const String HOME = 'assets/icons/home.png';
  static const String USER = 'assets/icons/user.png';
}
